### ISSUE TITLE
Java 9 specific issues

### ISSUE THREAD

**Issue by pal1000** [jpcsp/jpcsp#439]
These can only be reproduced when using JRE 9.0.1. It doesn't matter if it was compiled with JDK 8 or JDK 9.

1. A warning is thrown when opening UMD Brower:

```

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by jpcsp.GUI.UmdBrowser (file:/C:/Downloads/jpcsp-windows-amd64/bin/jpcsp.jar) to method sun.awt.image.PNGImageDecoder.setCheckCRC(boolean)
WARNING: Please consider reporting this to the maintainers of jpcsp.GUI.UmdBrowser
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

```

2. Using external software renderer crashes Java runtime.

**Comment by gid15** [comment]
The crash using the external software renderer should be fixed in "New jpcsp software renderer plugin revision 4183f4e". I have not found the real cause of the issue but could workaround it.

**Comment by pal1000** [comment]
I can confirm the crash has been solved. I built JPCSP with JDK 12.0.1 and apache ant 1.10.6.

**Comment by DragonNeos** [comment]
@gid15 On Java 9 and above, running any game that contains video will crash Java and JPCSP (when the video is being played). I have tried to run CRISIS CORE -FINAL FANTASY VII- on both 32-bit and 64-bit JPCSP and get the same result when the video is being played (albeit with different memory addresses).

32-bit:
```
# Problematic frame:
# J 7471 c2 jpcsp.media.codec.atrac3plus.ChannelUnit.decodeResidualSpectrum([[F)
V (541 bytes) @ 0x0000000003d446c9 [0x0000000003d44280+0x0000000000000449]
```

64-bit:
```
# Problematic frame:
# J 7102 c2 jpcsp.media.codec.atrac3plus.ChannelUnit.decodeResidualSpectrum([[F)
V (541 bytes) @ 0x000000000c4c3f59 [0x000000000c4c3a80+0x00000000000004d9]
```

[Java Console Crash on games with Video (32-bit).zip](https://github.com/jpcsp/jpcsp/files/5581070/Java.Console.Crash.on.games.with.Video.32-bit.zip)
[Java Console Crash on games with Video (64-bit).zip](https://github.com/jpcsp/jpcsp/files/5581072/Java.Console.Crash.on.games.with.Video.64-bit.zip)

**Comment by gid15** [comment]
It seems to be a bug in the JRE 9.0.4 as it is crashing in a java frame. I had no crash with JRE 11, please give it a try as JRE 9 is no longer updated/supported by Oracle.

**Comment by DragonNeos** [comment]
@gid15 There doesn't seem to be any issues when I use JRE 11.0.9. However, the same issue I mentioned in my previous post appears when I use JRE 15.0.1.

```
# Problematic frame:
# J 7736 c2 jpcsp.media.codec.atrac3plus.ChannelUnit.decodeResidualSpectrum([[F)
V (541 bytes) @ 0x000000000ae654da [0x000000000ae652a0+0x000000000000023a]
```
[Java 15.0.1+9 Console Crash on games with Video (64-bit).zip](https://github.com/jpcsp/jpcsp/files/5589590/Java.15.0.1%2B9.Console.Crash.on.games.with.Video.64-bit.zip)

**Comment by DragonNeos** [comment]
@gid15 JPCSP doesn't open when using Java 17.0.2. This message appears on the console screen after clicking the .bat file:

```
Running Jpcsp 64bit...
Exception in thread "GUI" java.lang.IllegalAccessError: class com.jidesoft.plaf.LookAndFeelFactory (in unnamed module @0x1cdc60d2)
cannot access class com.sun.java.swing.plaf.windows.WindowsLookAndFeel (in module java.desktop)
because module java.desktop does not export com.sun.java.swing.plaf.windows to unnamed module @0x1cdc60d2
        at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(LookAndFeelFactory.java:848)
        at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(LookAndFeelFactory.java:633)
        at jpcsp.MainGUI.initJide(MainGUI.java:321)
        at jpcsp.MainGUI.<init>(MainGUI.java:233)
        at jpcsp.MainGUI$78.run(MainGUI.java:3210)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

On Java 11.0.14, the emulator can open but it won't be able to load a game due to the LWJGL library not loading:
```
Running Jpcsp 64bit...
[LWJGL] Failed to load a library. Possible solutions:
        a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
        b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
Exception in thread "GUI" java.lang.UnsatisfiedLinkError: Failed to locate library: glfw.dll
        at org.lwjgl.system.Library.loadNative(Library.java:324)
        at org.lwjgl.system.Library.loadNative(Library.java:222)
        at org.lwjgl.glfw.GLFW.<clinit>(GLFW.java:674)
        at jpcsp.graphics.VideoEngineUtilities.updateMonitorContentScale(VideoEngineUtilities.java:110)
        at jpcsp.graphics.VideoEngineUtilities.drawFrameBuffer(VideoEngineUtilities.java:249)
        at jpcsp.graphics.VideoEngineUtilities.drawFromMemory(VideoEngineUtilities.java:285)
        at jpcsp.graphics.VideoEngineUtilities.drawFrameBufferFromMemory(VideoEngineUtilities.java:274)
        at jpcsp.HLE.modules.sceDisplay$AWTGLCanvas_sceDisplay.paintGL(sceDisplay.java:267)
        at org.lwjgl.opengl.awt.AWTGLCanvas.render(AWTGLCanvas.java:107)
        at jpcsp.HLE.modules.sceDisplay$AWTGLCanvas_sceDisplay.paint(sceDisplay.java:149)
        at java.desktop/java.awt.Canvas.update(Canvas.java:143)
        at java.desktop/sun.awt.RepaintArea.updateComponent(RepaintArea.java:255)
        at java.desktop/sun.awt.RepaintArea.paint(RepaintArea.java:232)
        at java.desktop/sun.awt.windows.WComponentPeer.handleEvent(WComponentPeer.java:358)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5072)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by gid15** [comment]
A few JDK issues have been fixed in d08c40c, 9577175, a63afac and 2e236b3.

**Comment by DragonNeos** [comment]
@gid15 On revision 051e9ac2, the startup issues still exist on both Java 11 and 17. The console window on both Java versions still shows errors about not being able to load the LWJGL library.

On Java 17, the following error message appears in the log:
```
18:25:30 ERROR  network - AutoDetectJpcsp - ListenerThread - ListenerThread
java.net.BindException: Cannot assign requested address: no further information
	at java.base/sun.nio.ch.Net.joinOrDrop4(Native Method)
	at java.base/sun.nio.ch.Net.join4(Net.java:698)
	at java.base/sun.nio.ch.DatagramChannelImpl.innerJoin(DatagramChannelImpl.java:1541)
	at java.base/sun.nio.ch.DatagramChannelImpl.join(DatagramChannelImpl.java:1559)
	at java.base/sun.nio.ch.DatagramSocketAdaptor.joinGroup(DatagramSocketAdaptor.java:535)
	at java.base/sun.nio.ch.DatagramSocketAdaptor.joinGroup(DatagramSocketAdaptor.java:481)
	at java.base/java.net.MulticastSocket.joinGroup(MulticastSocket.java:325)
	at jpcsp.network.upnp.AutoDetectJpcsp$ListenerThread.run(AutoDetectJpcsp.java:180)
```

I added the commands -Dorg.lwjgl.util.Debug=true and -Dorg.lwjgl.util.DebugLoader=true to the .bat file to see if it will help diagnose the problem.

After seeing that Java 11 and up requires the classpaths for all glfw files (lwjgl-glfw.jar/lwjgl-glfw-natives-platform.jar) to be added to the .bat file, I created a [Pull Request #492](https://github.com/jpcsp/jpcsp/pull/492) for it.

[jpcsp-051e9ac2-Console Error - Java 11.zip](https://github.com/jpcsp/jpcsp/files/8407274/jpcsp-051e9ac2-Console.Error.-.Java.11.zip)
[jpcsp-051e9ac2-Console Error - Java 17.zip](https://github.com/jpcsp/jpcsp/files/8407276/jpcsp-051e9ac2-Console.Error.-.Java.17.zip)
[LWJGL Debug Message.txt](https://github.com/jpcsp/jpcsp/files/8407278/LWJGL.Debug.Message.txt)
